src/pgzx/c/include/libpqsrv.h
src/pgzx/c/libpqsrv.c
src/pgzx/pq.zig

I found it a little difficult to work with separate types. Let's merge the sync and async interfaces into a common Conn type more similar to libpq.

libpq: common Conn type for sync and async ops

---

README.md
nix/templates/init/.envrc
nix/templates/init/.gitignore
nix/templates/init/README.md
nix/templates/init/build.zig
nix/templates/init/build.zig.zon
nix/templates/init/devshell.nix
nix/templates/init/extension/my_extension--0.1.sql
nix/templates/init/extension/my_extension.control
nix/templates/init/flake.nix
nix/templates/init/src/main.zig

Add nix flake based project template. This allows downstream users to have a development shell similar to pgzx and reuse some of our scripts. The template create a small functioning hello world based extension (without tests, thought).
The experience is still a little rough because Zig and Nix expect a public repository. For now I made the template so that it works with a local checkout.

Create project template

---

src/pgzx.zig
src/pgzx/collections.zig
src/pgzx/collections/htab.zig
src/pgzx/fmgr/conv.zig
src/pgzx/meta.zig
src/pgzx/pq/conv.zig
src/pgzx/testing.zig
src/testing.zig

Add typed wrappers for postgres HTAB type (`dynahash` hash tables that can also be used with shared memory).
When using HTAB one confiures an 'Entry' that can be any kind of struct. The prefix (first field) of the struct is supposed to hold the key. For string keys this means that we have to configure a max string length.

Dynahash: init support for Postgres Hash tables.

---

src/pgzx.zig
src/pgzx/meta.zig

Depends on #22 
I found the helpers in `meta` to be useful in downstream code. For now I'm exporting it under `pgzx.meta`. I wonder if we eventually want to introduce a `pgzx.lib` namespace for common utility functions that are not directly related to Postgres code.

Export `meta` module.

---

examples/pgaudit_zig/README.md
examples/pgaudit_zig/src/main.zig
src/pgzx/collections/dlist.zig
src/pgzx/collections/htab.zig
src/pgzx/collections/list.zig
src/pgzx/collections/slist.zig

Requires #22, #23
Rename `iter()` methods to `iterator()`. Zig std lib also uses `iterator()`, which allows me to use different container types downstream.

  rename: iter -> iterator 

---

flake.lock

Update zig compiler and zls via 
```
nix flake lock --update-input zig-overlay --update-input zls
```

Maintenance: update zig toolchain

---

build.zig.zon

Add missing `build.zig` file to list of exported paths. This fixes an issue where projects depending on pgzx can not import the pgzx build tools.

Package: Add build.zig to list of paths

---

src/pgzx/build.zig

There was a recent Zig update, removing a lot of the generic `std.os.*` functions, meaning we have to use `std.posix.getenv`.
I don't know if this will work on Windows, but from what I can tell, it should actually work.

Fix: replace os.getenv with posix.getenv

---

src/pgzx/pq.zig

leftover when we merge Sync/Async connection types into a common pq.Conn.

remove old `asSync`

---

src/pgzx/meta.zig
src/testing.zig

Add some more meta programming utility functions and tests.
Although the changes do not depend on any Postgres symbols I opted to add use our Postgres based test suite to register the tests. This way we do not introduce additional "entrypoints" into our testsuite.

Improve meta programming utilities and add tests

---

src/pgzx/collections/htab.zig

Collection hashtable: add valuesIterator

---

src/pgzx/c/include/libpqsrv.h
src/pgzx/c/libpqsrv.c
src/pgzx/pq.zig
src/pgzx/pq/conv.zig

Requires #37, #38
Use correct types in C helpers instead of `void*`. This also improve the Zig code as we do not have to cast between types and opaque pointer types.
export missing symbol.
Accept const pointers for our wrapper types. This makes it easier to use our wrapper type from within other types.

libpq improvements

---

ci/run.sh
examples/spi_sql/README.md
examples/spi_sql/build.zig
examples/spi_sql/build.zig.zon
examples/spi_sql/expected/spi_sql_test.out
examples/spi_sql/extension/spi_sql--0.1.sql
examples/spi_sql/extension/spi_sql.control
examples/spi_sql/sql/spi_sql_test.sql
examples/spi_sql/src/main.zig
src/pgzx/datum.zig
src/pgzx/spi.zig

Depends on #37, #38, #39
Fix import path in SPI module.
Add SPI testing extension to test suite to ensure SPI functioning correctly.

SPI: add test extension

---

examples/pgaudit_zig/src/main.zig
src/pgzx/mem.zig
src/pgzx/testing.zig
src/testing.zig

Add `pgzx.mem` unit tests to verify the API compiling/functioning as expected.
Fix `getErrorContext` not compiling.
API changes:
- Use configuration struct pattern to initialize the memory context allocator
- rename `new` to `init` to improve consistency. The methods have been hidden, but still
- improve `registerAllocResetCallback` type safety:
- rename to `registerAllocResetCallbackFn`
- introduce new method `registerAllocResetCallback` wrapper method that accepts a properly typed pointer and function doing. The wrapper implements that pointer cast. The function pointer is not required to implement the C calling convention (see `reset` unit test or `pg_audit_zig` updates)

pgzx.mem: Fix, improvements, tests

---

dev/docker/Dockerfile
dev/docker/build.sh
dev/docker/run.sh
flake.lock

Update zig toolchain
Update Docker image: Ubuntu images now have a default user `ubuntu`. I tried to update the Dockerfile to use the new user, but didn't get it functioning correctly. Instead for now I opted to delete the `ubuntu` user and keep the `dev` user an environment as is.

Update env: docker and flakes

---

src/pgzx/collections/list.zig

Add `iteratorFrom` and `reverseIteratorFrom` to create an iterator directly from a list type declaration.

List: add iteratorFrom

---

src/pgzx.zig
src/pgzx/fdw.zig

Requires #48, #49, #50
Implement `fdw.Options` related types and helper to validate options.
When implementing a foreign data wrapper one should implement a handler that returns a list of callbacks and a validator function that validates the settings FDW SQL statements will accept. So far the module only implements helpers for the validator.

 fdw: init submodule with helpers to implement foreign data wrappers 

---

src/pgzx/elog.zig

Sometimes we want to log an error after capturing another error.
Postgres errors and warnings are normally added to the error stack (default size 5). The top entry of the error stack can be flushed via `pg.EmitErrorReport`. Due to pgzx capturing errors and returning the `PGStackError` we do not immediately call emit right now.
With this change we introduce `XWithCause` functions to elog, like `LogWithCause`, `ErrorWithCause` and so on. These functions accept an existing Zig error. In case the error given is `PGStackError` we will call `pg.EmitErrorReport` to flush the original error. In case the error is not `PGStackError` we print the the error message and append the error code to the message like so: `<my error message>: <cause>`. This pattern allows us to use the `WithCause` functions …

elog: add XWithCause to include the cause in the error report

---

src/pgzx/fdw.zig

Empty list is indicated by `NIL`. We must accept an optional pointer in our Zig callback.

FDW: accept empty options list (NIL)

---

src/pgzx/pq.zig

fix method name not matching naming schema.

PQ: rename is_error method to isError

---

build.zig
src/pgzx.zig
src/pgzx/bgworker.zig
src/pgzx/collections/dlist.zig
src/pgzx/collections/htab.zig
src/pgzx/collections/list.zig
src/pgzx/collections/slist.zig
src/pgzx/datum.zig
src/pgzx/elog.zig
src/pgzx/err.zig
src/pgzx/fdw.zig
src/pgzx/fmgr.zig
src/pgzx/fmgr/args.zig
src/pgzx/interrupts.zig
src/pgzx/lwlock.zig
src/pgzx/mem.zig
src/pgzx/pq.zig
src/pgzx/pq/conv.zig
src/pgzx/pq/params.zig
src/pgzx/shmem.zig
src/pgzx/spi.zig
src/pgzx/testing.zig
src/pgzx/utils/guc.zig
src/pgzx/varatt.zig
src/testing.zig

Requires: #65 
With this change we split the C include and the `pgzx` into 2 modules:
- `pgzx_pgsys`: C includes and some custom C helpers
- `pgzx`: High level Zig utilities and abstractions.
The split is to prepare for code generation support. When generating Zig code on the fly the generated code is imported as a module into `pgzx`, but we also want the generated code to depend on the C includes. By splitting out the C support we can have the generated module import `pgsys` as a module dependency itself.
The change follows the pattern in https://github.com/ziglang/zig/blob/master/test/standalone/dep_triangle/build.zig
We still re-export `pgsys` under `pgzx.c`.
Within `pgzx` we replace `const c = @import(...)` with `const pg = @import("pgzx_pgsys");`. Now Postgres API usage is always …

pgsys module

---

build.zig
src/pgzx.zig
src/pgzx/c.zig
src/pgzx/node.zig
src/testing.zig
tools/gennodetags/main.zig

Requires #67 
Closes #66 
Postgres sources use tagging and the `Node` (and `NodeTag`) types for many internal types. Unfortunately the macros did not translate well to Zig, which makes it annoying to work with the low level types.
We introduce the `pgzx.node` module that provides a list of helper functions like `pgzx.node.make`, `pgzx.node.create`, `pgzx.node.tag`, or `pgzx.node.isA`.
We also wrap the constants into our own `pgzx.node.Tag` enum, so you can use `pgzx.node.isA(node, .Query)` in code.
Postgres uses code generation to collect the node tags and supported types into `nodetags.h`. We also use code generation to produce the list of tags and type mappings. The generated module is then imported by `pgzx.node`.
The `tools/gennodetags` tool imports the `nodes/nodes.h` header file at …

node: Introduce new module for working with postgres Node types

---

src/pgzx.zig
src/pgzx/fmgr.zig

I got tired of writing `PG_FUNCTION_V1`. The new `PG_EXPORT` helper looks up all public functions in a struct and automatically calls `PG_FUNCTION_V1` for you.
export public functions from a zig file:
```
pgzx.PG_EXPORT(@import("commands/pgd_onboard_remote_schema.zig"));
```
export public functions with anonymous struct:
```
pgzx.PG_EXPORT(struct{
pub fn hello() []const u8 { return "hello world"; }
pub fn add(a: i32, b: i32) i32 { return a + b; } 
}
```
Zig module with 'sqlexport' module:
```
comptime {
pgzx.PG_EXPORT(rpc.sqlexport)
}
```
with `rpc.zig`:
```
pub const sqlexport = struct {
...
};
// other module functions exported for reuse
```

fmgr: PG_EXPORT

---

ci/run.sh
examples/char_count_zig/ci/run.sh
examples/pgaudit_zig/ci/run.sh
examples/spi_sql/ci/run.sh

Create a ci/run.sh script per example. Eventually we might want to provide that functionality via the zig build system as extra tasks. But there are a few things that I would like to change in the build helpers that we have before adding test runners to it.
The main ci/run.sh script will build the examples in parallel now.

ci: run scripts per example

---

src/pgzx/pq.zig
src/pgzx/pq/conv.zig

The `exec` method now accepts a list of arguments.
Add `queryX` methods that directly return `Rows` for iterating over the results (similar to the SPI interface).
Add `Rows`, `Tuple`, `Field` and descriptor types to work with the results from a query.

pq: API improvements

---

src/pgzx/datum.zig
src/pgzx/fmgr/args.zig
src/pgzx/spi.zig

Add support to pass the values OID to the PG<->Zig type converter. This fixes issues with converting different string types to Zig types.
The SPI rows now also captures the SPI frame (the current tuple). This allows us to iterate over a tabletuple (list of rows) from a query while executing other statements via SPI.

datum: (optional) support for OIDs to convert between PG and ZIG types

---

src/pgzx/collections/list.zig

Add items functions that returns the underlying array. Sometimes it can be more convenient to access or iterate the elements using a normal slice.
Note: when adding elements the array can become invalid.

list: add items() method

---

examples/char_count_zig/build.zig
examples/pgaudit_zig/build.zig
examples/spi_sql/build.zig
examples/sqlfns/build.zig
src/pgzx/build.zig

Closes: #56 
Move `PGBuild.target` and `PGBuild.optimize` to `PGBuild.options` struct.
Introduce `PGBuild.modules` struct to load a the exported modules via simple function calls like `pgbuild.modules.pgzx()`.
Rename `Run` to `RunExec` to better indicate what that step does.
Simplify addRegress by removing the RunRegress type.
Introduce `addExtensionLib` to the shared lib to compile without installing it right away. This allows users to modify/use the lib with other targets that are not required to install the extension. For example a check target or build source documentation without linking and installation.
Introduce `Project` to combine the meta-data into a common type that can be used to create the different project resources within the build script. E.g. In order to create …

Build system improvements

---

dev/bin/pgbuild

postgres sources have been updated with a fix to the meson configuration. We do not need to apply our patch anymore. We still keep `patch` for users with older sources, but will not call that function anymore in the `configure` step.

pgbuild: make meson patch optional

---

build.zig.zon

The build system requires the `tools/gennodetags/main.zig` file, but since it's not included in the `build.zig.zon` file, anyone who adds `pgzx` as a dependency via `zig fetch` (or by specifying the url) will not be able to build their extension. It will fail with the following error: `error: unable to load '/home/guacs/.cache/zig/p/122078a0d7c7c1fc0cee07a61e8101509799873e1f46da165084cd9897f59303652b/tools/gennodetags/main.zig': FileNotFound`
As a workaround, copying the `tools` directory manually to the directory containing the source code that `zig` internally creates will work.

Add missing file in zon file

---

src/pgzx.zig
src/pgzx/collections/list.zig

Add `pgzx.listItemsOf` and `pgzx.collections.list.List.itemsOf` convenience helpers to make it easier to convert a postgres `List` to a Zig based typed slice.

collections: add helpers to convert List to zig slice

---

src/pgzx/node.zig

- Add constant value helpers like intVal, boolVal,...
- safeCastNode now accepts an optional node pointer as well. A `null` value will be converted into a properly typed `null` value of the target node type.

node: API improvements
